# Generated by Django 5.1.3 on 2025-04-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('politics', 'Politics'), ('entertainment', 'Entertainment'), ('share_market', 'Share Market')], default='sports', max_length=50),
            preserve_default=False,
        ),
    ]
