# Generated by Django 5.1.3 on 2025-04-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('politics', 'Politics'), ('entertainment', 'Entertainment'), ('share_market', 'Share Market')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
